apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cheetah-goes-cloud

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml


# ACHTUNG: Das funktioniert nur mit kubectl kustomize
helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    # version: "12.5.6"
    valuesInline:
      auth:
        username: # TODO
        password: # TODO
        database: notes
      fullnameOverride: "notes-db"
      primary:
        ## Disable security context is needed to run on OpenShift
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          size: 1Gi