replicaCount: 1
image:
  name: ghcr.io/gattma/cheetah-goes-cloud
  tag: "step1-3d7728e"
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
ingress:
  enabled: true
  basename: localdev.me
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
readinessProbe:
  enabled: true
  path: /q/health/ready
  timeoutSeconds: 2
  periodSeconds: 5
  failureThreshold: 30
  initialDelaySeconds: 10
livenessProbe:
  enabled: true
  path: /q/health/live
  timeoutSeconds: 2
  periodSeconds: 15
  failureThreshold: 3
  initialDelaySeconds: 60

postgresql:
  auth:
    username: # TODO
    password: # TODO
    database: notes
  fullnameOverride: "notes-db"
  primary:
    ## Disable security context is needed to run on OpenShift
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    persistence:
      size: 1Gi