apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cheetah-goes-cloud
spec:
  components:
    - name: cheetah-goes-cloud
      type: deployment
      properties:
        image: "ghcr.io/gattma/cheetah-goes-cloud"
        tag: "step1-3d7728e"
        ports:
          - port: 8080
            expose: true
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      traits:
        - type: db-connector
          properties:
            connectTo: notes-db

    - name: notes-db
      type: db-postgres # nachteil: passwort wird generiert, ändert sich zbsp. bei resync
      properties:
        user: cheetah
        database: notes