apiVersion: v1
kind: Service
metadata:
  name: {{ include "cheetah_goes_cloud.service.name" . }}
  labels:
    {{- include "cheetah_goes_cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cheetah_goes_cloud.selectorLabels" . | nindent 4 }}
