name: Release Containerimage

on: push

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test project with Maven
        run: mvn -B package -D skipTests --file src/cheetah-goes-cloud/pom.xml

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: push-container-image
        with:
          image: cheetah-goes-cloud
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: src/cheetah-goes-cloud/src/main/docker/Dockerfile.jvm
          directory:  src/cheetah-goes-cloud
          addLatest: true
          tags: ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }},latest